### ISSUE TITLE
String concat hello_world_ext.lm fail

### ISSUE THREAD

**Issue by mingodad** [adriandt/colm-suite#94]
Hello !
Just cloned colm-suite and going through the documentation and testing the "hello_world_ext.lm" we get this error:
```
colm "hello_world_ext.lm"
hello_world_ext.lm:1:26: hello_world_ext.lm: parse error: hello_world_ext.lm:1:26: parse error
```
Cheers !

**Comment by mingodad** [comment]
Also in the generated "0_06_scope.html" there is a repetion of the output from the first example "scope.lm" after the second example.

**Comment by mingodad** [comment]
Also in "2_03_def.html" the example assign.lm give this error:
```
colm "assign.lm"
assign.lm:2:9: assign.lm: parse error: assign.lm:2:9: parse error
```

**Comment by mingodad** [comment]
Hello !
I saw that you've made some changes and closed this issue, but it seems that it's still happening.
The "hello_world_ext.lm" still doesn't work:
```
print( 'hello ', "world" "\r\n" )
```
And also the "assign.lm":
```
lex start ////<<< here the "start" seems to no be valid here
```
Cheers !

**Comment by adriandt** [comment]
Hi @mingodad, it's still open. I'm new to github and clicked in the wrong place and accidentally assigned it to myself, then unassigned it. That's probably what you noticed.

The reason the hello world fails is described in #95.

The issue from assign.lm is due to out-of-date syntax. The lexical regions no longer have a name associated with them. There is no need to ever reference them by name, so I removed them.

I will fix both these issues in the documentation now.

**Comment by mingodad** [comment]
Ok !
Thanks for your great work !
I'm trying to compile colm in an Android device using Termux that comes with clang9 and it doesn't compile, I'm fixing it on my laptop and will fork and send a pull request just in case you are interested.
Cheers !

**Comment by adriandt** [comment]
For sure, absolutely interested in increasing portability!
